## 백준(20055번/실버1/구현) : 컨베이어 벨트 위의 로봇 / [문제 링크](https://www.acmicpc.net/problem/20055)

In [7]:
N, K = map(int, input().split())
# 내구도
A = list(map(int, input().split()))
# 로봇 유무
A2 = [0]*N

step = 0

while A.count(0) < K:
    step += 1
    # 한칸씩 이동
    # 해당 기능을 편하게 하려면 numpy.roll or deque.rotate를 활용하면 됨
    a = A.pop()
    A.insert(0, a)

    A2.pop()
    A2.insert(0, 0)
    
    # 로봇이 내려갈땐 자리가 비워짐
    A2[N-1] = 0

    # 컨베이어 벨트 회전
    for i in range(N-2, 0, -1):
        # 지금 칸에 로봇 있고, 다음칸에 내구도 있고, 다음칸에 로봇이 없으면
        if A2[i] and A[i+1] and (not A2[i+1]):
            # 지금칸의 로봇을 다음칸으로 옮겨주고
            A2[i] = 0
            A2[i+1] = 1
            # 다음칸의 내구도를 1 깎아준다
            A[i+1] = max(0, A[i+1]-1)

    # 로봇이 내려갈땐 자리가 비워짐
    A2[N-1] = 0

    # 첫칸에 내구도가 남아있고, 로봇이 없을때
    if A[0] and (not A2[0]):
        # 로봇을 채워주고
        A2[0] = 1
        # 내구도를 1 깎는다 근데 내구도가 0이면 -1이되어버리니까 max를 통해서 0으로 내려가는걸 방지해준다
        A[0] = max(0, A[0] - 1)

# 횟수 출력
print(step)

2


In [9]:
from collections import deque

items = deque([1, 2, 3])

for i in range(3):
    items.rotate(1)        # The deque is now: [3, 1, 2]
    print(items)

deque([3, 1, 2])
deque([2, 3, 1])
deque([1, 2, 3])


In [12]:
import numpy as np

a = np.arange(1,4) #Generate some data

for i in range(3):
    a = np.roll(a, 1)
    print(a)

[3 1 2]
[2 3 1]
[1 2 3]


In [ ]:
# 구현 알고리즘에서 자주 사용되는 2차원 배열에서 이동하는 알고리즘
# 이코테 영상보고 그냥 적어둠

# 동, 북, 서, 남
dx = [0, -1, 0, 1]
dy = [1, 0, -1, 0]

# 현재 워치
x, y = 2, 2

for i in range(4):
    # 다음 위치
    nx = x + dx[i]
    ny = y + dy[i]